name: Unity Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  UNITY_VERSION: '6000.0.38f1'
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}

jobs:
  # Android向けビルドとデプロイジョブ
  build-android:
    name: Build and Deploy Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      # ディスク容量の確保
      - name: Free disk space
        run: |
          sudo swapoff -a && sudo rm -f /swapfile
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc /usr/local/.ghcup
          sudo apt-get remove -y google-cloud-cli || sudo apt-get remove -y google-cloud-sdk
          sudo apt-get autoremove -y && sudo apt-get clean
          docker system prune -af
          df -h

      - name: Clean up Docker space
        run: docker system prune --volumes -a -f

      - name: Cache Unity Library - Android
        uses: actions/cache@v4.2.0
        with:
          path: Library
          key: Library-Android-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-Android-

      - name: Build Android App
        uses: game-ci/unity-builder@v4.3.0
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
          buildsPath: build
          buildName: MyAndroidApp
          androidExportType: androidPackage
          unityVersion: ${{ env.UNITY_VERSION }}

      - name: Upload Android Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Build-Android
          path: build/Android/MyAndroidApp.apk

      # Firebase App Distributionへのデプロイ（PRでない場合のみ）
      - name: Deploy to Firebase App Distribution
        if: github.event_name != 'pull_request'
        run: |
          # Google Cloud SDKのインストール
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates gnupg curl
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
            | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
            | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk

      # 3) Firebase CLI インストール (standalone)
      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
          firebase --version

      - name: Setup Service Account & Distribute
        run: |
          # 1) JSON を復元
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > service_account.json
          echo "Service Account JSON size: $(stat -c %s service_account.json) bytes"
          
          # 2) 変数をエクスポート (これでこのステップのシェルで認識される)
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service_account.json"
          
          # 3) Firebase CLI を使ってアップロード
          firebase appdistribution:distribute build/Android/MyAndroidApp.apk \
            --app ${{ secrets.FIREBASE_ANDROID_APP_ID }} \
            --groups "testers" \
            --release-notes "Release from GitHub Actions" \

  # WebGL向けビルドとデプロイジョブ (修正箇所に ★ マーク)
  build-webgl:
    name: Build and Deploy WebGL
    runs-on: ubuntu-latest
    # needs: build-android # 必要なら依存関係を設定
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      # ディスク容量の確保
      - name: Free disk space
        run: |
          sudo swapoff -a && sudo rm -f /swapfile
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc /usr/local/.ghcup
          sudo apt-get remove -y google-cloud-cli || sudo apt-get remove -y google-cloud-sdk
          sudo apt-get autoremove -y && sudo apt-get clean
          docker system prune -af
          df -h

      - name: Clean up Docker space
        run: docker system prune --volumes -a -f

      - name: Cache Unity Library - WebGL
        uses: actions/cache@v4.2.0
        with:
          path: Library
          key: Library-WebGL-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-WebGL-

      - name: Build WebGL App
        uses: game-ci/unity-builder@v4.3.0
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
          buildsPath: build
          buildName: WebGL
          unityVersion: ${{ env.UNITY_VERSION }}

      - name: Upload WebGL Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Build-WebGL
          path: build/WebGL # ★ ビルド出力先と合わせる
          retention-days: 14

      # ブランチ名からチャンネルIDを生成（PRでない場合のみ）
      - name: Generate Channel ID
        if: github.event_name != 'pull_request'
        id: channel
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          CHANNEL_ID=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed -e 's/[_\/]\+/-/g' -e 's/^-*//' -e 's/-*$//' -e 's/--*/-/g')
          CHANNEL_ID=$(echo "$CHANNEL_ID" | tr -cd 'a-z0-9-' | cut -c 1-36)
          if [[ "$BRANCH_NAME" == "main" ]]; then
            CHANNEL_ID="live"
          fi
          if [[ -z "$CHANNEL_ID" || "$CHANNEL_ID" == "-" ]]; then
            CHANNEL_ID="preview-${GITHUB_SHA::7}"
          fi
          echo "Generated Channel ID: $CHANNEL_ID"
          echo "CHANNEL_ID=$CHANNEL_ID" >> $GITHUB_ENV

      # Firebase CLI を使って Hosting にデプロイ（PRでない場合のみ）
      - name: Deploy to Firebase Hosting using CLI
        if: github.event_name != 'pull_request'
        run: |
          # Firebase CLI インストール
          if ! command -v firebase &> /dev/null; then
              echo "Firebase CLI not found, installing..."
              if ! command -v curl &> /dev/null; then sudo apt-get update && sudo apt-get install -y curl; fi
              curl -sL https://firebase.tools | bash
          fi
          firebase --version

          # サービスアカウントキー処理
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > service_account_webgl.json
          JSON_SIZE=$(stat -c %s service_account_webgl.json)
          echo "WebGL Service Account JSON size: $JSON_SIZE bytes"
          if [ "$JSON_SIZE" -lt 100 ]; then
            echo "Error: Failed to create valid WebGL service account file."
            cat service_account_webgl.json
            exit 1
          fi
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service_account_webgl.json"

          # --- デプロイコマンド ---
          FIREBASE_PROJECT="${{ env.FIREBASE_PROJECT_ID }}"
          if [ -z "$FIREBASE_PROJECT" ]; then
            echo "Error: FIREBASE_PROJECT_ID env var is not set."
            exit 1
          fi

          DEPLOY_CHANNEL="${{ env.CHANNEL_ID }}"
          # ★ 公開するディレクトリ（ビルド成果物の場所）
          DEPLOY_CHANNEL="${{ env.CHANNEL_ID }}"
          # ↓↓↓ ★★★ 公開ディレクトリのパスを修正 ★★★ ↓↓↓
          PUBLIC_DIR="build/WebGL/WebGL"

          echo "Creating temporary firebase.json with headers..."
          echo '{
            "hosting": {
              "public": "'"$PUBLIC_DIR"'",
              "ignore": [
                "firebase.json",
                "**/.*",
                "**/node_modules/**"
              ],
            }
          }' > firebase.json
          echo "Generated firebase.json:"
          cat firebase.json
          
          echo "Deploying to project '$FIREBASE_PROJECT' on channel '$DEPLOY_CHANNEL'"

          # チャンネルに応じたデプロイコマンド (変更なし)
          if [[ "$DEPLOY_CHANNEL" == "live" ]]; then
             echo "Deploying to production (live) channel..."
             firebase deploy \
               --project "$FIREBASE_PROJECT" \
               --only hosting \
               --message "Deploy build ${{ github.run_number }} from commit ${{ github.sha }} (branch: ${GITHUB_REF_NAME})" \
               --force \
               --debug
          else
             echo "Deploying to preview channel: $DEPLOY_CHANNEL"
             firebase hosting:channel:deploy "$DEPLOY_CHANNEL" \
               --project "$FIREBASE_PROJECT" \
               --only hosting \
               --expires 7d \
               --debug
          fi
          echo "Firebase deployment command executed."

        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
          CI: true

      # デプロイURL表示（PRでない場合のみ）
      - name: Output Deploy URL
        if: github.event_name != 'pull_request'
        run: |
          echo "WebGL build deployment process finished for channel: ${{ env.CHANNEL_ID }}"
          # channelId が 'live' の場合、本番URLを表示
          # それ以外はプレビューチャンネルのURLを表示
          if [[ "${{ env.CHANNEL_ID }}" == "live" ]]; then
            echo "Production URL: https://${{ env.FIREBASE_PROJECT_ID }}.web.app"
            echo "Production URL (firebaseapp.com): https://${{ env.FIREBASE_PROJECT_ID }}.firebaseapp.com"
          else
            echo "Preview URL: https://${{ env.FIREBASE_PROJECT_ID }}--${{ env.CHANNEL_ID }}.web.app"
            echo "Preview URL (firebaseapp.com): https://${{ env.FIREBASE_PROJECT_ID }}--${{ env.CHANNEL_ID }}.firebaseapp.com"
          fi